### ISSUE TITLE
Organisation strapline is a copy of EddieHub, please change

### ISSUE THREAD

**Issue by eddiejaoude** [Alphasians/Support#27]
<img width="969" alt="Screenshot 2021-09-19 at 09 58 52" src="https://user-images.githubusercontent.com/624760/133921690-8fd1c81e-4d85-4c06-900d-2960f00bfe9f.png">

**Comment by qwe123coder** [comment]
![image](https://user-images.githubusercontent.com/72848513/133926549-785c5094-e6b5-4fbc-9be1-b1f054942032.png)

**Comment by Sonichigo** [comment]
Thanks for letting me know!!
